.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LOUDGAIN" "1" "August 2019" "" ""
.
.SH "NAME"
\fBloudgain\fR \- loudness normalizer based on the EBU R128 standard
.
.SH "SYNOPSIS"
\fBloudgain [OPTIONS] FILES\.\.\.\fR
.
.SH "DESCRIPTION"
\fBloudgain\fR is a loudness normalizer that scans music files and calculates loudness\-normalized gain and loudness peak values according to the EBU R128 standard, and can optionally write ReplayGain\-compatible metadata\.
.
.P
loudgain implements a subset of mp3gain\'s command\-line options, which means that it can be used as a drop\-in replacement in some situations\.
.
.P
loudgain will \fInot\fR modify the actual audio data, but instead just write ReplayGain \fItags\fR if so requested\. It is up to the player to interpret these\. (In some players, you need to enable this feature\.)
.
.P
loudgain currently supports writing tags to the following file types:
.
.br
FLAC (\.flac), Ogg Vorbis (\.ogg), MP2 (\.mp2), MP3 (\.mp3), MP4 (\.mp4, \.m4a)\.
.
.SH "OPTIONS"
\fB\-h, \-\-help\fR
.
.P
\~\~\~\~\~\~ Show this help\.
.
.P
\fB\-v, \-\-version\fR
.
.P
\~\~\~\~\~\~ Show version number\.
.
.P
\fB\-r, \-\-track\fR
.
.P
\~\~\~\~\~\~ Calculate track gain only (default)\.
.
.P
\fB\-a, \-\-album\fR
.
.P
\~\~\~\~\~\~ Calculate album gain (and track gain)\.
.
.P
\fB\-c, \-\-clip\fR
.
.P
\~\~\~\~\~\~ Ignore clipping warnings\.
.
.P
\fB\-k, \-\-noclip\fR
.
.P
\~\~\~\~\~\~ Lower track/album gain to avoid clipping (<= \-1 dBTP)\.
.
.P
\fB\-K n, \-\-maxtpl=n\fR
.
.P
\~\~\~\~\~\~ Avoid clipping; max\. true peak level = n dBTP\.
.
.P
\fB\-d n, \-\-pregain=n\fR
.
.P
\~\~\~\~\~\~ Apply n dB/LU pre\-gain value (\-5 for \-23 LUFS target)\.
.
.P
\fB\-s d, \-\-tagmode=d\fR
.
.P
\~\~\~\~\~\~ Delete ReplayGain tags from files\.
.
.P
\fB\-s i, \-\-tagmode=i\fR
.
.P
\~\~\~\~\~\~ Write ReplayGain 2\.0 tags to files\. ID3v2 for MP2/MP3, Vorbis Comments for FLAC and Ogg Vorbis, iTunes\-type metadata for MP4\.
.
.P
\fB\-s e, \-\-tagmode=e\fR
.
.P
\~\~\~\~\~\~ like \'\-s i\', plus extra tags (reference, ranges)\.
.
.P
\fB\-s l, \-\-tagmode=l\fR
.
.P
\~\~\~\~\~\~ like \'\-s e\', but LU units instead of dB\.
.
.P
\fB\-s s, \-\-tagmode=s\fR
.
.P
\~\~\~\~\~\~ Don\'t write ReplayGain tags (default)\.
.
.P
\fB\-L, \-\-lowercase\fR
.
.P
\~\~\~\~\~\~ Force lowercase \'REPLAYGAIN_*\' tags (MP2/MP3/MP4 only; non\-standard)
.
.P
\fB\-S, \-\-striptags\fR
.
.P
\~\~\~\~\~\~ Strip tag types other than ID3v2 from MP2/MP3 files (i\.e\. ID3v1, APEv2)\.
.
.P
\fB\-I 3, \-\-id3v2version=3\fR
.
.P
\~\~\~\~\~\~ Write ID3v2\.3 tags to MP2/MP3 files\.
.
.P
\fB\-I 4, \-\-id3v2version=4\fR
.
.P
\~\~\~\~\~\~ Write ID3v2\.4 tags to MP2/MP3 files (default)\.
.
.P
\fB\-o, \-\-output\fR
.
.P
\~\~\~\~\~\~ Database\-friendly tab\-delimited list output (mp3gain\-compatible)\.
.
.P
\fB\-O, \-\-output\-new\fR
.
.P
\~\~\~\~\~\~ Database\-friendly new format tab\-delimited list output\.
.
.P
\fB\-q, \-\-quiet\fR
.
.P
\~\~\~\~\~\~ Don\'t print scanning status messages\.
.
.SH "AUTHORS"
Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.br
Matthias C\. Hormann \fImhormann@gmx\.de\fR
.
.SH "COPYRIGHT"
Copyright (C) 2014 Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.br
Everything after v0\.1: Copyright (C) 2019 Matthias C\. Hormann \fImhormann@gmx\.de\fR
.
.P
This program is released under the 2 clause BSD license\.
